"""Add phase 17 deep intelligence fields

Revision ID: b871a14d57ca
Revises: 
Create Date: 2025-12-21 01:27:44.632148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b871a14d57ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_cache', sa.Column('executives', sa.JSON(), nullable=True))
    op.add_column('company_cache', sa.Column('shareholders', sa.JSON(), nullable=True))
    op.add_column('company_cache', sa.Column('establishment_date', sa.DateTime(), nullable=True))
    op.add_column('company_cache', sa.Column('legal_form', sa.String(length=100), nullable=True))
    op.add_column('company_cache', sa.Column('activity_codes', sa.JSON(), nullable=True))
    op.add_column('company_cache', sa.Column('financials', sa.JSON(), nullable=True))
    op.add_column('company_cache', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('company_cache', sa.Column('contact_phone', sa.String(length=100), nullable=True))
    op.add_column('company_cache', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('company_cache', sa.Column('employees_count', sa.Integer(), nullable=True))
    op.add_column('company_cache', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_company_cache_last_synced_at'), 'company_cache', ['last_synced_at'], unique=False)
    op.add_column('favorite_companies', sa.Column('risk_factors', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.drop_column('favorite_companies', 'risk_factors')
    op.drop_index(op.f('ix_company_cache_last_synced_at'), table_name='company_cache')
    op.drop_column('company_cache', 'status')
    op.drop_column('company_cache', 'employees_count')
    op.drop_column('company_cache', 'website')
    op.drop_column('company_cache', 'contact_phone')
    op.drop_column('company_cache', 'contact_email')
    op.drop_column('company_cache', 'financials')
    op.drop_column('company_cache', 'activity_codes')
    op.drop_column('company_cache', 'legal_form')
    op.drop_column('company_cache', 'establishment_date')
    op.drop_column('company_cache', 'shareholders')
    op.drop_column('company_cache', 'executives')
    # ### end Alembic commands ###
