import React from "react";
import { Sparkles, Globe, Share2, Info } from "lucide-react";

const IntelligenceBrief = ({ story, metadata }) => {
  if (!story) return null;

  return (
    <div className="bg-white border border-slate-200 rounded-xl shadow-lg border-l-4 border-l-blue-600 overflow-hidden">
      <div className="bg-slate-50 px-4 py-3 border-b border-slate-200 flex items-center justify-between">
        <div className="flex items-center gap-2 font-bold text-slate-800">
          <Sparkles className="w-4 h-4 text-blue-600" />
          <span>Intelligence Brief</span>
        </div>
        {metadata?.is_cross_border && (
          <span className="flex items-center gap-1 text-[10px] bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full font-bold uppercase tracking-wider">
            <Globe className="w-3 h-3" />
            Cross-Border
          </span>
        )}
      </div>

      <div className="p-4">
        <p className="text-sm text-slate-700 leading-relaxed mb-4">{story}</p>

        {metadata && (
          <div className="grid grid-cols-2 gap-3 pt-3 border-t border-slate-100">
            <div className="flex flex-col">
              <span className="text-[10px] text-slate-400 uppercase font-bold">
                Network Nodes
              </span>
              <span className="text-sm font-semibold text-slate-800">
                {metadata.node_count}
              </span>
            </div>
            <div className="flex flex-col">
              <span className="text-[10px] text-slate-400 uppercase font-bold">
                Relationships
              </span>
              <span className="text-sm font-semibold text-slate-800">
                {metadata.edge_count}
              </span>
            </div>
            <div className="flex flex-col col-span-2">
              <span className="text-[10px] text-slate-400 uppercase font-bold">
                Countries Involved
              </span>
              <div className="flex gap-1 mt-1">
                {metadata.involved_countries?.map((c) => (
                  <span
                    key={c}
                    className="text-[10px] bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded border border-slate-200"
                  >
                    {c}
                  </span>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      <div className="bg-blue-50 px-4 py-2 flex items-center gap-2 text-[10px] text-blue-700">
        <Info className="w-3 h-3" />
        <span>Generated by Nexus Intelligence Engine</span>
      </div>
    </div>
  );
};

export default IntelligenceBrief;
